// Generated by gencpp from file qr_navigation/qrMsg.msg
// DO NOT EDIT!


#ifndef QR_NAVIGATION_MESSAGE_QRMSG_H
#define QR_NAVIGATION_MESSAGE_QRMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace qr_navigation
{
template <class ContainerAllocator>
struct qrMsg_
{
  typedef qrMsg_<ContainerAllocator> Type;

  qrMsg_()
    : header()
    , name()
    , id(0)  {
    }
  qrMsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , name(_alloc)
    , id(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef int32_t _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::qr_navigation::qrMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qr_navigation::qrMsg_<ContainerAllocator> const> ConstPtr;

}; // struct qrMsg_

typedef ::qr_navigation::qrMsg_<std::allocator<void> > qrMsg;

typedef boost::shared_ptr< ::qr_navigation::qrMsg > qrMsgPtr;
typedef boost::shared_ptr< ::qr_navigation::qrMsg const> qrMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::qr_navigation::qrMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::qr_navigation::qrMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace qr_navigation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'qr_navigation': ['/home/aaron/JA/code/LearningROS/opencv_learning/src/qr_navigation/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::qr_navigation::qrMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qr_navigation::qrMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qr_navigation::qrMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qr_navigation::qrMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qr_navigation::qrMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qr_navigation::qrMsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::qr_navigation::qrMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e29cd348083eeece3acb349d73ceb1cf";
  }

  static const char* value(const ::qr_navigation::qrMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe29cd348083eeeceULL;
  static const uint64_t static_value2 = 0x3acb349d73ceb1cfULL;
};

template<class ContainerAllocator>
struct DataType< ::qr_navigation::qrMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "qr_navigation/qrMsg";
  }

  static const char* value(const ::qr_navigation::qrMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::qr_navigation::qrMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
string name\n\
int32 id\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::qr_navigation::qrMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::qr_navigation::qrMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.name);
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct qrMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::qr_navigation::qrMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::qr_navigation::qrMsg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QR_NAVIGATION_MESSAGE_QRMSG_H
